#!/bin/sh

# --------------------------------------------------------------------------------
# base settings and variables
# --------------------------------------------------------------------------------
set -eu

# --------------------------------------------------------------------------------
# main
# --------------------------------------------------------------------------------

# set some defaults for testing, add a : before to make the script fail
#
OPENLDAP_ROOTPASS=${OPENLDAP_ROOTPASS:-"superSecurePassword"}
OPENLDAP_DOMAIN=${OPENLDAP_DOMAIN:-"example.org"}
OPENLDAP_ORGANISATION=${OPENLDAP_ORGANISATION:-"Example Org Inc."}

# restict slapd memory
ULIMIT_NOFILE_SYS=$(ulimit -Sn)
ULIMIT_NOFILE_SET=${OPENLDAP_NOFILE:-16384}
ULIMIT_NOFILE=$(( $ULIMIT_NOFILE_SYS < $ULIMIT_NOFILE_SET ? $ULIMIT_NOFILE_SYS : $ULIMIT_NOFILE_SET ))

echo >&2 "starting slapd"
ulimit -Sn "$ULIMIT_NOFILE"
exec /usr/sbin/slapd -h "ldap:///" -u openldap -g openldap -d 2 
